### ISSUE TITLE
Проверка директив модуля 1С

### ISSUE THREAD

**Issue by Pr-Mex** [silverbulleters/sonar-gherkin#2]
При анализе кода надо выявлять процедуры/функции, у которых строит директива 
&НаСервере
а должна быть
&НаСервереБезКонтекста

Т.е. разработчик забыл что можно не гонять лишний раз контекст на сервер.

Навеяно после разговора с @pumbaEO.

**Comment by nixel2007** [comment]
@Pr-Mex этот модуль для плагина поддержки Gherkin.

Идеи по доработке плагина поддержки 1C (BSL) на данный момент принимаются в личку и вешаются на внутреннюю доску :)

**Comment by allustin** [comment]
стоп... @nixel2007 а ведь верно. А почему бы не сделать публичку - не тут, а плагине sonar-l10n ?

**Comment by Pr-Mex** [comment]
@nixel2007 сори, не туда запостил
@allustin точно, надо паблик
